(()=>{
'use strict';
const B=window.BH;if(!B)return;
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
if(B.Save){const oldDefault=B.Save.default.bind(B.Save);B.Save.default=()=>oldDefault();B.Save.sanitize=function(input){const d=this.default(),s=Object.assign({},d,input||{});s.cash=Math.max(0,finite(input?.cash,d.cash));s.totalCash=Math.max(0,finite(input?.totalCash,d.totalCash));s.rebirth=Math.max(0,Math.floor(finite(input?.rebirth,0)));s.level=Math.max(1,Math.floor(finite(input?.level,1)));s.xp=Math.max(0,finite(input?.xp,0));s.creatures=Array.isArray(input?.creatures)?input.creatures.filter(Boolean):[];s.collection=input?.collection&&typeof input.collection==='object'?input.collection:{};s.quests=input?.quests&&typeof input.quests==='object'?input.quests:{};s.achievements=Array.isArray(input?.achievements)?input.achievements:[];s.cosmetics=Array.isArray(input?.cosmetics)?[...new Set(input.cosmetics)]:['starter-theme'];s.settings=Object.assign({},d.settings,input?.settings||{});s.baseCustomization=Object.assign({},d.baseCustomization,input?.baseCustomization||{});s.stats=Object.assign({},d.stats,input?.stats||{});return s}};
if(B.Stealing){B.Stealing.attempt=function(actor,targetBase,targetCreature){if(!actor||!targetBase||!targetCreature||actor.carrying)return false;if(B.Base.isLocked(targetBase))return false;if(Math.hypot(actor.x-targetBase.x,actor.y-targetBase.y)>105)return false;const mode=B.Game?.state?.settings?.botDifficulty||'NORMAL',chance=mode==='HARD'?.78:mode==='EASY'?.58:.68;if(Math.random()>chance)return false;const ownerId=targetBase.ownerId;if(!B.Base.remove(targetBase,targetCreature))return false;actor.carrying=targetCreature;targetCreature.state='CARRYING';targetCreature.originalOwnerId=ownerId;targetCreature.ownerId=actor.id;B.Game.state.stats.steals++;B.Quests?.add(B.Game.state,'steal');B.Notify.push(`${actor.name} stole ${targetCreature.name}!`,'ALERT');B.Audio.beep(220,.08,'sawtooth');return true};B.Stealing.deliver=function(actor){if(!actor?.carrying)return false;if(Math.hypot(actor.x-actor.base.x,actor.y-actor.base.y)>110)return false;const c=actor.carrying;if(B.Base.freeIndex(actor.base)<0)return false;actor.carrying=null;c.state='OWNED';c.originalOwnerId=null;B.Base.put(actor.base,c);if(actor.type!=='bot'){B.Game.state.stats.successfulSteals++;B.Quests?.add(B.Game.state,'steal')}B.Notify.toast(`${actor.name} delivered ${c.name}!`);B.Audio.success();return true};B.Stealing.recover=function(actor){if(!actor?.carrying)return false;const c=actor.carrying,owner=B.Game.players.find(p=>p.id===c.originalOwnerId);actor.carrying=null;const base=owner?.base||actor.base;c.state='OWNED';c.ownerId=base.ownerId;c.originalOwnerId=null;const ok=B.Base.put(base,c);if(ok)B.Notify.push('Creature recovered!','SUCCESS');return ok}};
if(B.Rebirth){B.Rebirth.cost=function(target){const r=typeof target==='number'?target:(target?.type==='bot'?target.rebirth:target?.rebirth??0);return Math.round(B.Config.rebirth.base*Math.pow(B.Config.rebirth.growth,Math.max(0,r)))};B.Rebirth.do=function(state,player){if(!player)return false;const cost=this.cost(player);if(finite(player.cash)<cost)return false;player.cash=B.Config.START_CASH;player.rebirth=(player.rebirth||0)+1;const keep=player.base.slots.filter(Boolean).sort((a,b)=>b.price-a.price).slice(0,2),newMax=Math.min(27,Math.max(6,B.Config.START_SLOTS+Math.floor(player.rebirth/2)));player.base.maxSlots=newMax;player.base.slots=Array(newMax).fill(null);for(const c of keep)B.Base.put(player.base,c);if(player.type!=='bot'){state.cash=player.cash;state.rebirth=player.rebirth;state.stats.rebirths++;B.Achievements?.check(state);B.Quests?.add(state,'rebirth')}B.Notify.push(`${player.name} rebirthed!`,'EVENT');return true}};
B.RNGUI={open(){B.UI.modal('Reward Terminal','<div class="card"><b>SAFE REWARD</b><p class="muted">Fixed gameplay reward. No paid or wagering system.</p><button id="safeReward">CLAIM</button></div>');document.getElementById('safeReward').onclick=()=>{B.Reward.claim(B.Game.player);B.UI.close()}}};
window.handleAction=function(a){if(a==='play'){document.getElementById('menu').classList.add('hidden');B.Game.init();return}if(a==='index')B.IndexUI.open();else if(a==='shop')B.ShopUI.open();else if(a==='settings')B.SettingsUI.open();else if(a==='rewards')B.RNGUI.open();else if(a==='fusion')B.FusionUI.open();else if(a==='stats')B.StatsUI.open();else if(a==='rebirth')B.RebirthUI.open();else if(a==='save'){B.Save.save(B.Game.serialize());B.Notify.toast('Saved')}else if(a==='menu'){B.UI.close();B.Save.save(B.Game.serialize());location.reload()}};
if(B.Game){const oldUpdate=B.Game.update.bind(B.Game);B.Game.update=function(dt){oldUpdate(dt);for(const bot of this.players.slice(1)){bot.totalCash=finite(bot.totalCash)+Math.max(0,finite(B.Economy.totalIncome(bot,this.state,this.activeEvent))*dt)}if(this.player?.base?.slots){this.state.creatures=this.player.base.slots.filter(Boolean).map(c=>({...c}));this.state.collection=this.state.collection||{};for(const c of this.player.base.slots.filter(Boolean))this.state.collection[c.id]=true}}}
})();
